export const CREATE_MACHINE_TYPE = "CREATE_MACHINE_TYPE";
export const RETRIEVE_MACHINE_TYPES = "RETRIEVE_MACHINE_TYPES";
export const UPDATE_MACHINE_TYPE = "UPDATE_MACHINE_TYPE";
export const DELETE_MACHINE_TYPE = "DELETE_MACHINE_TYPE";
export const DELETE_ALL_MACHINE_TYPES = "DELETE_ALL_MACHINE_TYPES";
