export const RETRIEVE_REQUESTS = "RETRIEVE_REQUESTS";
export const CREATE_REQUEST = "CREATE_REQUEST";
export const DELETE_REQUEST = "DELETE_REQUEST";
export const DELETE_ALL_REQUESTS = "DELETE_ALL_REQUESTS";
export const UPDATE_REQUESTS = "UPDATE_REQUESTS";
