export const CREATE_CONTRACT = "CREATE_CONTRACT";
export const RETRIEVE_CONTRACTS = "RETRIEVE_CONTRACTS";
export const UPDATE_CONTRACT = "UPDATE_CONTRACT";
export const DELETE_CONTRACT = "DELETE_CONTRACT";
export const DELETE_ALL_CONTRACTS = "DELETE_ALL_CONTRACTS";