export const CREATE_COMPANY = "CREATE_COMPANY";
export const RETRIEVE_COMPANIES = "RETRIEVE_COMPANIES";
export const UPDATE_COMPANY = "UPDATE_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
export const DELETE_ALL_COMPANIES = "DELETE_ALL_COMPANIES";