export const CREATE_MACHINE = "CREATE_MACHINE";
export const RETRIEVE_MACHINES = "RETRIEVE_MACHINES";
export const UPDATE_MACHINE = "UPDATE_MACHINE";
export const DELETE_MACHINE = "DELETE_MACHINE";
export const DELETE_ALL_MACHINES = "DELETE_ALL_MACHINES";