export const RETRIEVE_LOCATIONS = "RETRIEVE_LOCATIONS";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const CREATE_LOCATION = "CREATE_LOCATION";
export const DELETE_ALL_LOCATION = "DELETE_ALL_LOCATION";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
