export const CREATE_DRIVER = "CREATE_DRIVER";
export const RETRIEVE_DRIVERS = "RETRIEVE_DRIVERS";
export const UPDATE_DRIVER = "UPDATE_DRIVER";
export const DELETE_DRIVER = "DELETE_DRIVER";
export const DELETE_ALL_DRIVERS = "DELETE_ALL_DRIVERS";